# Generated by Django 3.2.13 on 2022-05-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rating_videoclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoclass_list', to='api.course'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('courses', models.ManyToManyField(related_name='course_list', to='api.Course')),
            ],
        ),
    ]
