# Generated by Django 3.2.13 on 2022-05-25 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220525_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='course_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
