# Generated by Django 3.2.13 on 2022-05-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(default='courses_covers/image_example.jpg', upload_to='courses_covers/'),
            preserve_default=False,
        ),
    ]
